services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: /bin/sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 task_management_backend.wsgi:application"

  frontend:
    image: "node:22"
    user: "node"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    command: /bin/sh -c "yarn install --frozen-lockfile && yarn start"

