# Generated by Django 5.0.7 on 2024-07-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status_todotask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktitle',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
