# Generated by Django 5.0.7 on 2024-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status_alter_tasktitle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
