# Generated by Django 5.0.7 on 2024-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_status_alter_tasktitle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('started', 'started'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktitle',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
